monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - websocket    # Add a dedicated channel for WebSocket logs
        - access_log # All request response pairs are logged here to enable controle 

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
                formatter: monolog.formatter.line
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            websocket:
                type: rotating_file
                path: "%kernel.logs_dir%/websocket.log"  # Path for WebSocket logs
                max_files: 10
                level: debug
                channels: ["websocket"]  # Log WebSocket events here
            access_log:
                type: rotating_file
                path: "%kernel.logs_dir%/access.log"
                max_files: 10
                level: info
                channels: ["access_log"]
                formatter: monolog.formatter.json

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            websocket:
                type: stream
                path: "%kernel.logs_dir%/websocket.log"  # Log WebSocket events in test environment
                level: debug
                channels: ["websocket"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            websocket:
                type: stream
                path: "%kernel.logs_dir%/websocket.log"  # Log WebSocket events in prod environment
                level: debug
                channels: ["websocket"]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
